import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, basename, relative } from "node:path";
import matter from "gray-matter";
import { encode } from "gpt-tokenizer";

const SPEC_DIR = process.env.ADAM_SPEC_DIR ?? join(process.cwd(), "spec");

if (!existsSync(SPEC_DIR)) {
  console.error(`[adam-reindex] no spec dir at ${SPEC_DIR}`);
  process.exit(0);
}

type Row = {
  name: string;
  description: string;
  agents: string[];
  tokens: number;
  path: string;
};

const files = readdirSync(SPEC_DIR)
  .filter((f) => f.endsWith(".md") && f !== "INDEX.md")
  .map((f) => join(SPEC_DIR, f));

const rows: Row[] = [];

for (const path of files) {
  const raw = readFileSync(path, "utf8");
  const parsed = matter(raw);
  const fm = parsed.data as Record<string, unknown>;
  const body = parsed.content;
  const tokens = encode(body).length;

  if (fm.tokens !== tokens) {
    fm.tokens = tokens;
    const rewritten = matter.stringify(body, fm);
    writeFileSync(path, rewritten);
  }

  rows.push({
    name: (fm.name as string) ?? basename(path, ".md"),
    description: (fm.description as string) ?? "",
    agents: Array.isArray(fm.agents) ? (fm.agents as string[]) : [],
    tokens,
    path,
  });
}

const totalTokens = rows.reduce((s, r) => s + r.tokens, 0);

const header =
  "# Spec Index\n\n" +
  "<!-- adam-managed:start -->\n" +
  "This file is regenerated by `/spec`, `/spec-create`, `/spec-dream`, and `/adam:setup`. Do not hand-edit the table below — edit individual `spec/*.md` files instead.\n\n" +
  "| spec | description | agents | tokens |\n" +
  "|---|---|---|---|\n";

const body = rows
  .map((r) => {
    const rel = relative(SPEC_DIR, r.path);
    const agents = r.agents.join(", ") || "—";
    const desc = r.description.replace(/\|/g, "\\|");
    return `| [${r.name}](./${rel}) | ${desc} | ${agents} | ${r.tokens} |`;
  })
  .join("\n");

const footer = `\n\n_Total: ${rows.length} specs, ${totalTokens} tokens._\n<!-- adam-managed:end -->\n`;

writeFileSync(join(SPEC_DIR, "INDEX.md"), header + body + footer);

console.log(`[adam-reindex] ${rows.length} specs, ${totalTokens} tokens → ${SPEC_DIR}/INDEX.md`);
